# docker-compose.yml
version: '3.8'
services:
  api-gateway:
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_DEBUG=True
      - SECRET_KEY=your-secret-key
      - REDIS_URL=redis://redis:6379/0
      - S3_ENDPOINT_URL=http://minio:9000
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin
      - S3_BUCKET=transcoding-bucket
    depends_on:
      - redis
      - minio
    volumes:
      - ./services/api-gateway:/app
      - ./services/common:/app/common  # Mount common utilities

  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - FLASK_DEBUG=True
      - SECRET_KEY=your-secret-key
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    volumes:
      - ./services/auth-service:/app
      - ./services/common:/app/common  # Mount common utilities

  upload-service:
    build:
      context: ./services/upload-service
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    environment:
      - FLASK_DEBUG=True
      - REDIS_URL=redis://redis:6379/0
      - S3_ENDPOINT_URL=http://minio:9000
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin
      - S3_BUCKET=transcoding-bucket
    depends_on:
      - redis
      - minio
    volumes:
      - ./services/upload-service:/app
      - ./services/common:/app/common  # Mount common utilities

  transcoding-service:
    build:
      context: ./services/transcoding-service
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379/0
      - S3_ENDPOINT_URL=http://minio:9000
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin
      - S3_BUCKET=transcoding-bucket
    depends_on:
      - redis
      - minio
    volumes:
      - ./services/transcoding-service:/app
      - ./services/common:/app/common  # Mount common utilities
      # Temporary storage for transcoding
      - transcoding-tmp:/tmp

  notification-service:
    build:
      context: ./services/notification-service
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379/0
      - SMTP_HOST=smtp.gmail.com  # Example: Gmail SMTP
      - SMTP_PORT=587
      - SMTP_USER=your-gmail@gmail.com  # Replace with your Gmail
      - SMTP_PASSWORD=your-app-password  # Replace with Gmail App Password
    depends_on:
      - redis
    volumes:
      - ./services/notification-service:/app
      - ./services/common:/app/common  # Mount common utilities

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"  # MinIO Console
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

volumes:
  redis-data:
  minio-data:
  transcoding-tmp:  # Temporary storage for transcoding files