# ./docker-compose.yml
version: '3.8'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - FLASK_DEBUG=True
      - SECRET_KEY=client-secret-key
      - STANDALONE_MODE=False
      - GOOGLE_CLIENT_ID=your-google-client-id
      - GOOGLE_CLIENT_SECRET=your-google-client-secret
      - GITHUB_CLIENT_ID=your-github-client-id
      - GITHUB_CLIENT_SECRET=your-github-client-secret
      - REDIRECT_URI=http://localhost:8000/callback
    depends_on:
      - api-gateway
    volumes:
      - ./client:/app

  api-gateway:
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_DEBUG=True
      - SECRET_KEY=your-secret-key
      - REDIS_URL=redis://redis:6379/0
      - S3_ENDPOINT_URL=http://minio:9000
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin
      - S3_BUCKET=transcoding-bucket
    depends_on:
      - redis
      - minio
    volumes:
      - ./services/api-gateway:/app
      - ./services/common:/app/common

  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - FLASK_DEBUG=True
      - SECRET_KEY=your-secret-key
      - REDIS_URL=redis://redis:6379/0
      - GOOGLE_CLIENT_ID=your-google-client-id
      - GOOGLE_CLIENT_SECRET=your-google-client-secret
      - GITHUB_CLIENT_ID=your-github-client-id
      - GITHUB_CLIENT_SECRET=your-github-client-secret
      - REDIRECT_URI=http://localhost:5001/auth/callback
    depends_on:
      - redis
    volumes:
      - ./services/auth-service:/app
      - ./services/common:/app/common

  upload-service:
    build:
      context: ./services/upload-service
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    environment:
      - FLASK_DEBUG=True
      - REDIS_URL=redis://redis:6379/0
      - S3_ENDPOINT_URL=http://minio:9000
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin
      - S3_BUCKET=transcoding-bucket
    depends_on:
      - redis
      - minio
    volumes:
      - ./services/upload-service:/app
      - ./services/common:/app/common

  transcoding-service:
    build:
      context: ./services/transcoding-service
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379/0
      - S3_ENDPOINT_URL=http://minio:9000
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin
      - S3_BUCKET=transcoding-bucket
    depends_on:
      - redis
      - minio
    volumes:
      - ./services/transcoding-service:/app
      - ./services/common:/app/common
      - transcoding-tmp:/tmp

  notification-service:
    build:
      context: ./services/notification-service
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379/0
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=your-gmail@gmail.com
      - SMTP_PASSWORD=your-app-password
    depends_on:
      - redis
    volumes:
      - ./services/notification-service:/app
      - ./services/common:/app/common

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

volumes:
  redis-data:
  minio-data:
  transcoding-tmp: