# ./infrastructure/kubernetes/base/services/notification-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: media-transcoding
spec:
  type: ClusterIP
  ports:
  - port: 4004
    targetPort: 4004
  selector:
    app: notification-service