# ./infrastructure/kubernetes/base/services/transcoding-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: transcoding-service
  namespace: media-transcoding
spec:
  type: ClusterIP
  ports:
  - port: 4003
    targetPort: 4003
  selector:
    app: transcoding-service