# ./infrastructure/kubernetes/services/notification-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: notification-service:latest
        env:
        - name: REDIS_URL
          value: "redis://redis:6379/0"
        - name: SMTP_HOST
          value: "" # smtp.example.com
        - name: SMTP_PORT
          value: "587"
        - name: SMTP_USER
          value: "" # email@example.com
        - name: SMTP_PASSWORD
          value: "" # email-password
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-service
  ports:
  - port: 5004
    targetPort: 5004
  type: ClusterIP