# ./infrastructure/kubernetes/services/transcoding-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transcoding-service
  labels:
    app: transcoding-service
spec:
  replicas: 2  # Scale for parallel transcoding
  selector:
    matchLabels:
      app: transcoding-service
  template:
    metadata:
      labels:
        app: transcoding-service
    spec:
      containers:
      - name: transcoding-service
        image: transcoding-service:latest
        env:
        - name: REDIS_URL
          value: "redis://redis:6379/0"
        - name: S3_ENDPOINT_URL
          value: "http://minio:9000"
        - name: S3_ACCESS_KEY
          value: "minioadmin"
        - name: S3_SECRET_KEY
          value: "minioadmin"
        - name: S3_BUCKET
          value: "transcoding-bucket"
---
apiVersion: v1
kind: Service
metadata:
  name: transcoding-service
spec:
  selector:
    app: transcoding-service
  ports:
  - port: 5003  # Internal port for Celery workers
    targetPort: 5003
  type: ClusterIP