# ./infrastucture/kubernetes/services/upload-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-service
  labels:
    app: upload-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upload-service
  template:
    metadata:
      labels:
        app: upload-service
    spec:
      containers:
      - name: upload-service
        image: upload-service:latest
        ports:
        - containerPort: 5002
        env:
        - name: S3_ENDPOINT_URL
          value: "http://minio:9000"
        - name: S3_ACCESS_KEY
          value: "minioadmin"
        - name: S3_SECRET_KEY
          value: "minioadmin"
        - name: S3_BUCKET
          value: "transcoding-bucket"
        - name: REDIS_URL
          value: "redis://redis:6379/0"
---
apiVersion: v1
kind: Service
metadata:
  name: upload-service
spec:
  selector:
    app: upload-service
  ports:
  - port: 5002
    targetPort: 5002
  type: ClusterIP